# Generated by Django 2.2.7 on 2019-11-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.TextField(default='public default', max_length=100),
        ),
    ]
