# Generated by Django 2.2.7 on 2019-11-21 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_auto_20191121_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ForeignKey(default='public', on_delete=django.db.models.deletion.CASCADE, related_name='message_group', to='sns.Group'),
        ),
    ]
